namespace robot.sl.Audio.AudioPlaying
{
    public enum AudioName
    {
        Welcome,
        Vor,
        Zurueck,
        Links,
        Rechts,
        Stop,
        Wenden,
        LeichtLinks,
        LeichtRechts,
        GanzLeichtLinks,
        GanzLeichtRechts,
        Langsam,
        Normal,
        Schnell,
        Tanzen,
        Befehl,
        StarkeVibration,
        Steht,
        AutomatischesFahrenFesthaengen,
        Restart,
        Shutdown,
        StartAutomaticDrive,
        StopAutomaticDrive,
        ReallyRestart,
        ReallyShutdown,
        GamepadVibrationOn,
        GamepadVibrationOff,
        AppError,

        SoundModeAlreadyOn,
        HeadsetSpeakerOff,
        HeadsetSpeakerAlreadyOff,
        HeadsetSpeakerOn,
        HeadsetSpeakerAlreadyOn,
        CarSpeakerOff,
        CarSpeakerAlreadyOff,
        CarSpeakerOn,
        CarSpeakerAlreadyOn,
        AllSpeakerOff,
        AllSpeakerAlreadyOff,
        AllSpeakerOn,
        AllSpeakerAlreadyOn,
        SoundModeOn,
        SoundModusAlreadyOff,
        SoundModusOff,

        CarSpeakerOffHeadsetSpeakerOnSoundModeOff,
        CarSpeakerOnHeadsetSpeakerOffSoundModeOff,
        CarSpeakerOffHeadsetSpeakerOnSoundModeOn,
        CarSpeakerOnHeadsetSpeakerOffSoundModeOn,
        AllSpeakerOffSoundModeOff,
        AllSpeakerOffSoundModeOn,
        AllSpeakerOnSoundModeOff,
        AllSpeakerOnSoundModeOn,

        Steuerungsbefehle,
        Systembefehle,

        CameraUp,
        CameraDown,
        CameraLightUp,
        CameraLightDown,

        TurnToLongLeft,
        TurnToLongRight
    }
}
